alertmanager:
  image: prom/alertmanager:latest

  container_name: alertmanager

  restart: unless-stopped

  ports:
    - "9093:9093"

  volumes:
    - ./alertmanager:/etc/alertmanager

  command:
    - "--config.file=/etc/alertmanager/alertmanager.yml"
